#! /bin/sh

# Define desktops
bspc monitor eDP-1  -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X

# Select monitor layout
~/bin/homemon
#~/bin/workmon

# Solid background color.
hsetroot -solid '#1e1c55'

# Basic display.
bspc config border_width          0
bspc config window_gap            6
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config focused_border_color  '#513fbf'

# External rules.
bspc config external_rules_command ~/.config/bspwm/split-rule

# Compositor.
pkill picom
picom --experimental-backends -b

# Polybar.
pkill polybar
~/.config/polybar/launch.sh

# Key mapper.
pkill sxhkd
sxhkd &

