#!/usr/bin/bash

# Define desktops and select monitors.
CFGTYPE=$(~/bin/get-desktop-cfg)
if [ $? -ne 0 ] ; then
    ~/bin/lapmon
else
    case "$CFGTYPE" in
        WORK) ~/bin/workmon ;;
        HOME) ~/bin/homemon ;;
        *)    ~/bin/lapmon  ;;
    esac
fi

# Solid background color.
hsetroot -solid '#1e1c55'
xsetroot -cursor_name left_ptr

# Basic display.
bspc config border_width          0
bspc config window_gap            6
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config focused_border_color  '#513fbf'

# Rules.
bspc rule -a Blueman-manager state=floating
bspc rule -a Meld state=floating

# External rules.
bspc config external_rules_command ~/.config/bspwm/split-rule

# Compositor.
#pkill picom
#picom --experimental-backends -b

# Key mapper.
pkill sxhkd
sxhkd &

