#!/bin/sh

# Below taken from https://imgur.com/a/PgkHTvU.
#
# Some example inputs:
#   $1 -> 0x00801963
#   $2 -> URxvt
#   $3 -> vim
#   $4 -> concatenation of below settings
#
# Some example outputs (subset of consequence inputs):
#   monitor=
#   desktop=0x00C0000C
#   node=
#   state=fullscreen
#   layer=
#   split_dir=
#   split_ratio=0.00000
#   hidden=off
#   sticky=off
#   private=off
#   locked=off
#   marked=off
#   center=off
#   follow=off
#   manage=on
#   focus=on
#   border=on
#   rectangle=

wid=$1
class=$2
instance=$3
consequences=$4

DIRFILE=~/.bspwm.split_dir
if [ -f "$DIRFILE" ] ; then
    DIR=`cat $DIRFILE`
    echo "split_dir=$DIR split_ratio=0.50"
fi 

